# Generated by Django 2.0 on 2017-12-21 08:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bbsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', tinymce.models.HTMLField(verbose_name='文章详情')),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='content',
        ),
        migrations.AddField(
            model_name='post_details',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbsapp.Posts', verbose_name='所属文章'),
        ),
    ]
